= APK Automatic Updates

The aim of *apk-autoupdate* is to keep the system up-to-date.
It checks available updates, installs them and restarts affected services.
The tool is intended to be executed automatically and regularly by cron or similar tool.

apk-autoupdate is designed to be flexible and highly customizable.
Its configuration file is based on shell and provides many hooks allowing you to adjust each step to your needs (see link:man/autoupdate.conf.5.adoc[autoupdate.conf(5)]).


== Manuals

* link:man/apk-autoupdate.1.adoc[apk-autoupdate(1)]
* link:man/procs-need-restart.1.adoc[procs-need-restart(1)]
* link:man/autoupdate.conf.5.adoc[autoupdate.conf(5)]


== Requirements

.*Runtime*:
* Linux system with `/proc`
* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[POSIX-sh] compatible shell with support for `set -e pipefail`, `local` and `readonly` (e.g. Busybox ash, ZSH, bash, …, sadly not dash)
* https://github.com/alpinelinux/apk-tools/[apk-tools]
* common userland with `awk`, `grep`, `head`, `ps`, `sed` (e.g. from Busybox, GNU coreutils, …)

.*Build*:
* C compiler and linker supporting at least C99 (tested with clang and gcc)
* https://www.gnu.org/software/make/[GNU Make]
* http://asciidoctor.org/[Asciidoctor] (for building man pages)


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
